// Code generated by MockGen. DO NOT EDIT.
// Source: git_accessor.go
//
// Generated by this command:
//
//	mockgen -source git_accessor.go -package commit -destination git_accessor_mock_test.go
//

// Package commit is a generated GoMock package.
package commit

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockgitOperationsAccessor is a mock of gitOperationsAccessor interface.
type MockgitOperationsAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockgitOperationsAccessorMockRecorder
	isgomock struct{}
}

// MockgitOperationsAccessorMockRecorder is the mock recorder for MockgitOperationsAccessor.
type MockgitOperationsAccessorMockRecorder struct {
	mock *MockgitOperationsAccessor
}

// NewMockgitOperationsAccessor creates a new mock instance.
func NewMockgitOperationsAccessor(ctrl *gomock.Controller) *MockgitOperationsAccessor {
	mock := &MockgitOperationsAccessor{ctrl: ctrl}
	mock.recorder = &MockgitOperationsAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitOperationsAccessor) EXPECT() *MockgitOperationsAccessorMockRecorder {
	return m.recorder
}

// BeginStaging mocks base method.
func (m *MockgitOperationsAccessor) BeginStaging(excludePatterns, includePatterns []string, useGlobalGitignore bool) (*stagingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginStaging", excludePatterns, includePatterns, useGlobalGitignore)
	ret0, _ := ret[0].(*stagingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginStaging indicates an expected call of BeginStaging.
func (mr *MockgitOperationsAccessorMockRecorder) BeginStaging(excludePatterns, includePatterns, useGlobalGitignore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginStaging", reflect.TypeOf((*MockgitOperationsAccessor)(nil).BeginStaging), excludePatterns, includePatterns, useGlobalGitignore)
}

// CreateCommit mocks base method.
func (m *MockgitOperationsAccessor) CreateCommit(session *stagingSession, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommit", session, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCommit indicates an expected call of CreateCommit.
func (mr *MockgitOperationsAccessorMockRecorder) CreateCommit(session, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommit", reflect.TypeOf((*MockgitOperationsAccessor)(nil).CreateCommit), session, message)
}

// CreateTag mocks base method.
func (m *MockgitOperationsAccessor) CreateTag(tag, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", tag, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockgitOperationsAccessorMockRecorder) CreateTag(tag, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockgitOperationsAccessor)(nil).CreateTag), tag, message)
}

// FinishStaging mocks base method.
func (m *MockgitOperationsAccessor) FinishStaging(session *stagingSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishStaging", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishStaging indicates an expected call of FinishStaging.
func (mr *MockgitOperationsAccessorMockRecorder) FinishStaging(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishStaging", reflect.TypeOf((*MockgitOperationsAccessor)(nil).FinishStaging), session)
}

// GetConflictedFiles mocks base method.
func (m *MockgitOperationsAccessor) GetConflictedFiles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConflictedFiles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConflictedFiles indicates an expected call of GetConflictedFiles.
func (mr *MockgitOperationsAccessorMockRecorder) GetConflictedFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConflictedFiles", reflect.TypeOf((*MockgitOperationsAccessor)(nil).GetConflictedFiles))
}

// GetCurrentBranch mocks base method.
func (m *MockgitOperationsAccessor) GetCurrentBranch() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranch")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranch indicates an expected call of GetCurrentBranch.
func (mr *MockgitOperationsAccessorMockRecorder) GetCurrentBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranch", reflect.TypeOf((*MockgitOperationsAccessor)(nil).GetCurrentBranch))
}

// GetLatestTag mocks base method.
func (m *MockgitOperationsAccessor) GetLatestTag() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTag")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTag indicates an expected call of GetLatestTag.
func (mr *MockgitOperationsAccessorMockRecorder) GetLatestTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTag", reflect.TypeOf((*MockgitOperationsAccessor)(nil).GetLatestTag))
}

// GetRepoState mocks base method.
func (m *MockgitOperationsAccessor) GetRepoState() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoState")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoState indicates an expected call of GetRepoState.
func (mr *MockgitOperationsAccessorMockRecorder) GetRepoState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoState", reflect.TypeOf((*MockgitOperationsAccessor)(nil).GetRepoState))
}

// GetStagedDiff mocks base method.
func (m *MockgitOperationsAccessor) GetStagedDiff(maxSizeBytes int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStagedDiff", maxSizeBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStagedDiff indicates an expected call of GetStagedDiff.
func (mr *MockgitOperationsAccessorMockRecorder) GetStagedDiff(maxSizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStagedDiff", reflect.TypeOf((*MockgitOperationsAccessor)(nil).GetStagedDiff), maxSizeBytes)
}

// HasConflicts mocks base method.
func (m *MockgitOperationsAccessor) HasConflicts() (bool, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasConflicts")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HasConflicts indicates an expected call of HasConflicts.
func (mr *MockgitOperationsAccessorMockRecorder) HasConflicts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasConflicts", reflect.TypeOf((*MockgitOperationsAccessor)(nil).HasConflicts))
}

// IncrementVersion mocks base method.
func (m *MockgitOperationsAccessor) IncrementVersion(currentTag, incrementType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVersion", currentTag, incrementType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementVersion indicates an expected call of IncrementVersion.
func (mr *MockgitOperationsAccessorMockRecorder) IncrementVersion(currentTag, incrementType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVersion", reflect.TypeOf((*MockgitOperationsAccessor)(nil).IncrementVersion), currentTag, incrementType)
}

// IsGitRepository mocks base method.
func (m *MockgitOperationsAccessor) IsGitRepository() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGitRepository")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsGitRepository indicates an expected call of IsGitRepository.
func (mr *MockgitOperationsAccessorMockRecorder) IsGitRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGitRepository", reflect.TypeOf((*MockgitOperationsAccessor)(nil).IsGitRepository))
}

// Push mocks base method.
func (m *MockgitOperationsAccessor) Push() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockgitOperationsAccessorMockRecorder) Push() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockgitOperationsAccessor)(nil).Push))
}

// PushTag mocks base method.
func (m *MockgitOperationsAccessor) PushTag(tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushTag indicates an expected call of PushTag.
func (mr *MockgitOperationsAccessorMockRecorder) PushTag(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTag", reflect.TypeOf((*MockgitOperationsAccessor)(nil).PushTag), tag)
}
