// Code generated by MockGen. DO NOT EDIT.
// Source: accessors.go
//
// Generated by this command:
//
//	mockgen -source accessors.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockproviderAccessor is a mock of providerAccessor interface.
type MockproviderAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockproviderAccessorMockRecorder
	isgomock struct{}
}

// MockproviderAccessorMockRecorder is the mock recorder for MockproviderAccessor.
type MockproviderAccessorMockRecorder struct {
	mock *MockproviderAccessor
}

// NewMockproviderAccessor creates a new mock instance.
func NewMockproviderAccessor(ctrl *gomock.Controller) *MockproviderAccessor {
	mock := &MockproviderAccessor{ctrl: ctrl}
	mock.recorder = &MockproviderAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproviderAccessor) EXPECT() *MockproviderAccessorMockRecorder {
	return m.recorder
}

// Ask mocks base method.
func (m *MockproviderAccessor) Ask(ctx context.Context, prompt string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ask", ctx, prompt)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ask indicates an expected call of Ask.
func (mr *MockproviderAccessorMockRecorder) Ask(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockproviderAccessor)(nil).Ask), ctx, prompt)
}

// IsAvailable mocks base method.
func (m *MockproviderAccessor) IsAvailable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockproviderAccessorMockRecorder) IsAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockproviderAccessor)(nil).IsAvailable))
}

// Name mocks base method.
func (m *MockproviderAccessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockproviderAccessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockproviderAccessor)(nil).Name))
}

// SetTimeout mocks base method.
func (m *MockproviderAccessor) SetTimeout(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimeout", timeout)
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockproviderAccessorMockRecorder) SetTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockproviderAccessor)(nil).SetTimeout), timeout)
}

// MockmoduleAccessor is a mock of moduleAccessor interface.
type MockmoduleAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockmoduleAccessorMockRecorder
	isgomock struct{}
}

// MockmoduleAccessorMockRecorder is the mock recorder for MockmoduleAccessor.
type MockmoduleAccessorMockRecorder struct {
	mock *MockmoduleAccessor
}

// NewMockmoduleAccessor creates a new mock instance.
func NewMockmoduleAccessor(ctrl *gomock.Controller) *MockmoduleAccessor {
	mock := &MockmoduleAccessor{ctrl: ctrl}
	mock.recorder = &MockmoduleAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmoduleAccessor) EXPECT() *MockmoduleAccessorMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockmoduleAccessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockmoduleAccessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockmoduleAccessor)(nil).Name))
}

// TransformCommitMessage mocks base method.
func (m *MockmoduleAccessor) TransformCommitMessage(ctx context.Context, branch, message string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformCommitMessage", ctx, branch, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TransformCommitMessage indicates an expected call of TransformCommitMessage.
func (mr *MockmoduleAccessorMockRecorder) TransformCommitMessage(ctx, branch, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformCommitMessage", reflect.TypeOf((*MockmoduleAccessor)(nil).TransformCommitMessage), ctx, branch, message)
}

// TransformPrompt mocks base method.
func (m *MockmoduleAccessor) TransformPrompt(ctx context.Context, prompt string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformPrompt", ctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TransformPrompt indicates an expected call of TransformPrompt.
func (mr *MockmoduleAccessorMockRecorder) TransformPrompt(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformPrompt", reflect.TypeOf((*MockmoduleAccessor)(nil).TransformPrompt), ctx, prompt)
}

// MockaiServiceAccessor is a mock of aiServiceAccessor interface.
type MockaiServiceAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockaiServiceAccessorMockRecorder
	isgomock struct{}
}

// MockaiServiceAccessorMockRecorder is the mock recorder for MockaiServiceAccessor.
type MockaiServiceAccessorMockRecorder struct {
	mock *MockaiServiceAccessor
}

// NewMockaiServiceAccessor creates a new mock instance.
func NewMockaiServiceAccessor(ctrl *gomock.Controller) *MockaiServiceAccessor {
	mock := &MockaiServiceAccessor{ctrl: ctrl}
	mock.recorder = &MockaiServiceAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaiServiceAccessor) EXPECT() *MockaiServiceAccessorMockRecorder {
	return m.recorder
}

// GenerateCommitMessages mocks base method.
func (m *MockaiServiceAccessor) GenerateCommitMessages(ctx context.Context, diff, branch string, files, providers []string, customPrompt string, first, multiLine bool) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCommitMessages", ctx, diff, branch, files, providers, customPrompt, first, multiLine)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCommitMessages indicates an expected call of GenerateCommitMessages.
func (mr *MockaiServiceAccessorMockRecorder) GenerateCommitMessages(ctx, diff, branch, files, providers, customPrompt, first, multiLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCommitMessages", reflect.TypeOf((*MockaiServiceAccessor)(nil).GenerateCommitMessages), ctx, diff, branch, files, providers, customPrompt, first, multiLine)
}

// NumProviders mocks base method.
func (m *MockaiServiceAccessor) NumProviders() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumProviders")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumProviders indicates an expected call of NumProviders.
func (mr *MockaiServiceAccessorMockRecorder) NumProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumProviders", reflect.TypeOf((*MockaiServiceAccessor)(nil).NumProviders))
}
