---

name: unified-workflow

on:
  # manual trigger
  workflow_dispatch:
  # push or merge to master
  push:
    branches:
      - master
  # pull request targeting master branch created or updated
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  golangci-lint:
    if: github.event_name == 'workflow_dispatch' || !endsWith(github.actor, '[bot]')
    uses: ./.github/workflows/110-golangci-lint.yaml
    with:
      runs_on: ubuntu-latest
      continue_on_error: false

  unit-tests:
    uses: ./.github/workflows/120-unit-tests.yaml
    needs:
      - golangci-lint
    with:
      runs_on: ubuntu-latest
      continue_on_error: false

  e2e-tests:
    uses: ./.github/workflows/125-e2e-tests.yaml
    needs:
      - golangci-lint
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
