---

name: e2e-tests

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: 'runs_on'
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: 'continue_on_error'
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean

permissions: {}

jobs:
  e2e-tests:
    name: e2e-tests
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5
      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: 'Download Go modules'
        run: go mod download
      - name: 'Run black-box end-to-end tests'
        run: make test-e2e
        env:
          CGO_ENABLED: 1 # needed for -race
